### ISSUE TITLE
Dropdown in Flatlist I'm getting error

### ISSUE THREAD

**Issue by NareshNama** [amituidev/lib4dev#10]
this._scrollRef.scrollTo is not a function

**Comment by amituidev** [comment]
Which dropdown  i'm not getting any error can you attach the screenshot ?

**Comment by NareshNama** [comment]
![simulator screen shot - iphone 6 - 2018-10-10 at 14 46 21](https://user-images.githubusercontent.com/42469119/46726174-6c134700-cc9b-11e8-8eb9-8705f5ca42e5.png)
Dropdown in modal

**Comment by amituidev** [comment]
Are you developing something? Which library are you using?

**Comment by NareshNama** [comment]
using 'react-native-material-dropdown'; library

**Comment by amituidev** [comment]
Hey http://www.lib4dev.com is only displaying the github repositories. lib4dev is not maintaining the repos. If you have any issue then contact to repos author.
