### ISSUE TITLE
issue for react-native-multiple-select

### ISSUE THREAD

**Issue by sowji123456** [amituidev/lib4dev#12]
for me nothing is displayed it is displaying just blank 
here is my snippet
 <View style={{ flex:1 }}>
        <MultiSelect
 items={this.items}
 uniqueKey="id" ref={(component) => { this.multiSelect= component }}
 onSelectedItemsChange={this.onSelectedItemsChange}
 selectedItems={selectedItems}
 selectText="Pick Items" searchInputPlaceholderText="Search Items..." onChangeInput={ (text)=>console.log(text)}
 altFontFamily="ProximaNova-Light" tagRemoveIconColor="#CCC" tagBorderColor="#CCC" tagTextColor="#CCC" selectedItemTextColor="#CCC" selectedItemIconColor="#CCC" itemTextColor="#000" displayKey="name" searchInputStyle={{ color:'#CCC' }}
 submitButtonColor="#CCC" submitButtonText="Submit"/>

        <View>{this.multiSelect && this.multiSelect.getSelectedItemsExt(selectedItems)}</View>
                </View>

**Comment by amituidev** [comment]
Hey http://www.lib4dev.com is only displaying the github repositories. lib4dev is not maintaining the repos. If you have any issue then contact to repos author
